---
# Ansible Galaxy requirements

collections:
  - name: community.general
    version: ">=7.0.0"
  - name: community.libvirt
    version: ">=1.0.0"
  - name: maxhoesel.pterodactyl

roles:
  - name: geerlingguy.nut_client
    src: https://github.com/geerlingguy/ansible-role-nut_client.git
    version: master
